version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: dashboard-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --requirepass "minha_senha_devJ+GMu1cN|IZ\"J33m[58g|8^8W" --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'minha_senha_devJ+GMu1cN|IZ"J33m[58g|8^8W', 'ping']
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  redis-data:
    driver: local
